---
- name: Create Deployment and Service in Kubernetes
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    deployment_name: xyz-deployment
    service_name: xzy-service
    app_image: xyz-app:latest
    app_port: 8080
    node_port: 32000

  tasks:
    - name: Create Deployment
      k8s:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          creationTimestamp: null
          labels:
            app: xyztechnologies-app
          name: xyztechnologies-app
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: xyztechnologies-app
          strategy: {}
          template:
            metadata:
              creationTimestamp: null
              labels:
                app: xyztechnologies-app
            spec:
              containers:
              - image: zayeed91/tomcat-server-xyz-technologies:1.0.0
                name: tomcat-server-xyz-technologies
                resources: {}
        status: {}

    - name: Create Service
      k8s:
        apiVersion: v1
        kind: Service
        metadata:
          creationTimestamp: null
          labels:
            app: xyztechnologies-app
          name: xyztechnologies-svc
        spec:
          ports:
          - port: 8080
            protocol: TCP
            targetPort: 8080
            nodePort: 32002
          selector:
            app: xyztechnologies-app
          type: NodePort
        status:
          loadBalancer: {}
