---
- name: Create Deployment and Service in Kubernetes
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    deployment_name: xyz-deployment
    service_name: xzy-service
    app_image: xyz-app:latest
    app_port: 8080
    node_port: 32000

  tasks:
    - name: Create Deployment
      k8s:
        api_version: apps/v1
        kind: Deployment
        metadata:
            namespace: default
            name: "{{ deployment_name }}"
            labels:
                app: "{{ deployment_name }}"
        namespace: default
        name: "{{ deployment_name }}"
        labels:
          app: "{{ deployment_name }}"
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: "{{ deployment_name }}"
          template:
            metadata:
              labels:
                app: "{{ deployment_name }}"
            spec:
              containers:
                - name: "{{ deployment_name }}"
                  image: "{{ app_image }}"
                  ports:
                    - containerPort: "{{ app_port }}"

    - name: Create Service
      k8s:
        apiVersion: v1
        kind: Service
        metadata:
          creationTimestamp: null
          labels:
            app: xyztechnologies-app
          name: xyztechnologies-svc
        spec:
          ports:
          - port: 8080
            protocol: TCP
            targetPort: 8080
            nodePort: 32002
          selector:
            app: xyztechnologies-app
          type: NodePort
        status:
          loadBalancer: {}
