apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: xyztechnologies-app
  name: xyztechnologies-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32002
  selector:
    app: xyztechnologies-app
  type: NodePort
status:
  loadBalancer: {}
